### ISSUE TITLE
[Bug] In multi GPU setup, tokens are assigned to the wrong device. 

### ISSUE THREAD

**Issue by prof-schacht** [jbloomAus/SAEDashboard#22]
Error: Runtime Error Indices should be on the same device or on cpu. 
Setup: GPU Server with 3xH100 80 GB

Goal Model inference should be on coda:0,1 and SAE on coda:2. ActivationStore on CPU.

During the run of the SAEDashboard, the TransformerLensWrapper has the token for encoding not on the devices coda:0 or 1 where ne model is allocated rather on the cuda:2 device.

Ways to reproduce. 
1. I loaded my SAE Trained on Phi-3 locally from this repo: https://huggingface.co/coai/sae_phi-3_mini_4k_ins_blocks_16_hook_resid_post_1B_tokens
2. Configured the SAEDasboard runner using this script:

`
import os
import torch

from sae_dashboard.neuronpedia.neuronpedia_runner import (
    NeuronpediaRunner,
    NeuronpediaRunnerConfig,
)

NP_OUTPUT_FOLDER = "neuronpedia_outputs/"
ACT_CACHE_FOLDER = "cached_activations"
NP_SET_NAME = "phi3-mini-res-16L-65k"
SAE_SET = "phi3-mini-res-16L-65k"
SAE_PATH = "/proj/checkpoint_vis/final_1024000000"
NUM_FEATURES_PER_BATCH = 2
NUM_BATCHES = 2
HF_DATASET_PATH = "coai/dclm-baseline-subset_100k"

SPARSITY_THRESHOLD = 1

SAE_DTYPE = "float32"
MODEL_DTYPE = "float32"

N_PROMPTS = 64
N_TOKENS_IN_PROMPT = 2048
N_PROMPTS_IN_FORWARD_PASS = 128

os.system(f"rm -rf {NP_OUTPUT_FOLDER}")
os.system(f"rm -rf {ACT_CACHE_FOLDER}")

cfg = NeuronpediaRunnerConfig(
    sae_set="local",
    sae_path=SAE_PATH,
    np_set_name=NP_SET_NAME,
    from_local_sae=True,
    huggingface_dataset_path=HF_DATASET_PATH,
    sae_dtype=SAE_DTYPE,
    model_dtype=MODEL_DTYPE,
    outputs_dir=NP_OUTPUT_FOLDER,
    sparsity_threshold=SPARSITY_THRESHOLD,
    n_prompts_total=N_PROMPTS,
    n_tokens_in_prompt=N_TOKENS_IN_PROMPT,
    n_prompts_in_forward_pass=N_PROMPTS_IN_FORWARD_PASS,
    n_features_at_a_time=NUM_FEATURES_PER_BATCH,
    start_batch=0,
    use_wandb=True,
    # sis
    activation_store_device = "cpu",
    model_device = "cuda",
    model_n_devices = 2,
    sae_device = "cuda:2",
    # TESTING ONLY
    end_batch=6,
)

runner = NeuronpediaRunner(cfg)
runner.run()
` 

And get these errors:

![image (1)](https://github.com/user-attachments/assets/caf48e20-04cb-4af9-8023-14bd55b30bf8)

After reducing the context-size and manually move the tokens on tokenlenswrapper line 81 to tokens.to("coda:0"). Then in debugging wat step further is working but as soon the second GPU (Model is distributed to two GPUs) jumps in, there is another index error:

<img width="1396" alt="image" src="https://github.com/user-attachments/assets/17794ba7-abbf-4b09-9e0f-f0b8dd6f71ce">

**Comment by jbloomAus** [comment]
@curt-tigges can you please solve this? Shouldn't be too complex.
